# Exceptiuon-- is an event which will cause pogram termination
# try:
# except:
# else:
# finally:

#Ex-1
# try:
#     num=0
#     num1=12
#     if num1/num==0:
#         print("not okay")
# except Exception as e:
#     print(e)
# try:
#     print("one.......")
#     print("second...........")
#     print("three........")
#     print(x)
#     print("four............")
#     print("five")
# except Exception as e:
#     print(e)

#ex-2
# try:
#     print(10/0)
# except ZeroDivisionError:
#     print("Exception handled..")

#Ex-3
#try - except-else:-finally
# try:
#     num=int(input("enter tputhe in:"))
#     num1=int(input("enter the input:"))
#     print(num/num1)
# except ZeroDivisionError:
#     print("zero...hendled")
# except SyntaxError:
#     print("syntax...handled")
# except:
#     print("No exception")
# else:
#     print("Exception no more")
# finally:
#     print("completed")

